export const dummyAnak = [
  {
    user_id: 1,
    nama_anak: 'Anak 1',
    // berat_badan: 15,
    // tinggi_badan: 100,
    tanggal_lahir: new Date(new Date().setFullYear(new Date().getFullYear() - 3)),
    createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 3)),
    updatedAt: new Date(new Date().setFullYear(new Date().getFullYear() - 3)),
  },
  {
    user_id: 1,
    nama_anak: 'Anak 2',
    // berat_badan: 18,
    // tinggi_badan: 110,
    tanggal_lahir: new Date(new Date().setFullYear(new Date().getFullYear() - 4)),
    createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 4)),
    updatedAt: new Date(new Date().setFullYear(new Date().getFullYear() - 4)),
  },
  {
    user_id: 1,
    nama_anak: 'Anak 3',
    // berat_badan: 20,
    // tinggi_badan: 115,
    tanggal_lahir: new Date(new Date().setFullYear(new Date().getFullYear() - 5)),
    createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 5)),
    updatedAt: new Date(new Date().setFullYear(new Date().getFullYear() - 5)),
  },
  {
    user_id: 1,
    nama_anak: 'Anak 4',
    // berat_badan: 22,
    // tinggi_badan: 120,
    tanggal_lahir: new Date(new Date().setFullYear(new Date().getFullYear() - 2)),
    createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 2)),
    updatedAt: new Date(new Date().setFullYear(new Date().getFullYear() - 2)),
  },
  {
    user_id: 1,
    nama_anak: 'Anak 5',
    // berat_badan: 25,
    // tinggi_badan: 125,
    tanggal_lahir: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
    createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
    updatedAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
  },
  {
    user_id: 2,
    nama_anak: 'Anak 6',
    // berat_badan: 16,
    // tinggi_badan: 105,
    tanggal_lahir: new Date(new Date().setFullYear(new Date().getFullYear() - 3)),
    createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 3)),
    updatedAt: new Date(new Date().setFullYear(new Date().getFullYear() - 3)),
  },
  {
    user_id: 2,
    nama_anak: 'Anak 7',
    // berat_badan: 19,
    // tinggi_badan: 112,
    tanggal_lahir: new Date(new Date().setFullYear(new Date().getFullYear() - 4)),
    createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 4)),
    updatedAt: new Date(new Date().setFullYear(new Date().getFullYear() - 4)),
  },
  {
    user_id: 2,
    nama_anak: 'Anak 8',
    // berat_badan: 21,
    // tinggi_badan: 118,
    tanggal_lahir: new Date(new Date().setFullYear(new Date().getFullYear() - 5)),
    createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 5)),
    updatedAt: new Date(new Date().setFullYear(new Date().getFullYear() - 5)),
  },
  {
    user_id: 2,
    nama_anak: 'Anak 9',
    // berat_badan: 23,
    // tinggi_badan: 122,
    tanggal_lahir: new Date(new Date().setFullYear(new Date().getFullYear() - 2)),
    createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 2)),
    updatedAt: new Date(new Date().setFullYear(new Date().getFullYear() - 2)),
  },
  {
    user_id: 2,
    nama_anak: 'Anak 10',
    // berat_badan: 26,
    // tinggi_badan: 128,
    tanggal_lahir: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
    createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
    updatedAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
  },
]
